import mongoose from "mongoose";
import appointmentModel from "../models/appointment.model";
import doctorPatientModel from "../models/doctorPatient.model";
import ReportModel from "../models/report.model";

// DOCTORS ANALYTICS
export const doctorsAnalytics = async (doctorId: string) => {
  try {
    const today = new Date();

    const todayDateOnly = today.toISOString().split("T")[0];
    const startOfToday = new Date(todayDateOnly + "T00:00:00.000Z");
    const endOfToday = new Date(todayDateOnly + "T23:59:59.999Z");

    // Total patients connected to this doctor
    const totalPatients = await doctorPatientModel.countDocuments({ doctorId });

    // Pending appointments (all upcoming pending)
    const pendingAppointments = await appointmentModel.countDocuments({
      doctorId,
      status: "pending",
    });

    // Reports generated by doctor
    const generatedReports = await ReportModel.countDocuments({ doctorId });

    // Today's appointments
    const todaysAppointments = await appointmentModel.countDocuments({
      doctorId,
      date: { $gte: startOfToday, $lte: endOfToday },
    });

    return {
      success: true,
      analytics: {
        totalPatients,
        pendingAppointments,
        generatedReports,
        todaysAppointments,
      },
      date: {
        today: todayDateOnly,
        startOfToday: startOfToday.toISOString(),
        endOfToday: endOfToday.toISOString(),
      },
      message: "Analytics fetched successfully",
    };
  } catch (error: any) {
    return {
      success: false,
      message: error.message,
    };
  }
};

// REPORTS + APPOINTMENTS LAST 7 DAYS ANALYTICS
export const reportsAppointmentsAnalytics = async (doctorId: string) => {
  try {
    
    const today = new Date();

    // 6 days before today
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(today.getDate() - 6);

    // Set starting time to 00:00:00
    sevenDaysAgo.setHours(0, 0, 0, 0);

    // REPORTS ANALYTICS
    const reportsAnalytics = await ReportModel.aggregate([
      {
        $match: {
          doctorId: new mongoose.Types.ObjectId(doctorId),
          createdAt: {
            $gte: sevenDaysAgo,
          },
        },
      },
      {
        $group: {
          _id: {
            $dateToString: {
              format: "%Y-%m-%d",
              date: "$createdAt",
            },
          },
          count: {
            $sum: 1,
          },
        },
      },
    ]);

    // APPOINTMENTS ANALYTICS
    const appointmentsAnalytics = await appointmentModel.aggregate([
      {
        $match: {
          doctorId: new mongoose.Types.ObjectId(doctorId),
          createdAt: {
            $gte: sevenDaysAgo,
          },
        },
      },
      {
        $group: {
          _id: {
            $dateToString: {
              format: "%Y-%m-%d",
              date: "$createdAt",
            },
          },
          count: {
            $sum: 1,
          },
        },
      },
    ]);

    // Create last 7 days array
    const last7Days: string[] = [];

    for (let i = 6; i >= 0; i--) {
      const date = new Date();
      date.setDate(today.getDate() - i);

      const formattedDate = date.toISOString().split("T")[0];
      last7Days.push(formattedDate);
    }

    // Convert analytics into arrays
    const reports = last7Days.map((day) => {
      const found = reportsAnalytics.find((item) => item._id === day);
      return found ? found.count : 0;
    });

    const appointments = last7Days.map((day) => {
      const found = appointmentsAnalytics.find((item) => item._id === day);
      return found ? found.count : 0;
    });

    return {
      success: true,
      message: "Successfully analytics fetched",
      data: {
        reports,
        appointments,
      },
    };
  } catch (error: any) {
    return {
      success: false,
      message: error.message,
    };
  }
};
