import mongoose from "mongoose";
import ReportModel from "../models/report.model";
import UserModel from "../models/user.model";

// CREATE REPORT
export const createReport = async (reportData: any) => {
  try {
    const {
      doctorId,
      patientId,
      xRayImage,
      keyFindings,
      heartSize,
      normalHeartSize,
      risk,
      aiConfidence,
      doctorNotes,
      status,
      title,
      description,
    } = reportData;

    // Validate doctorId & patientId
    if (!doctorId || !patientId) {
      return {
        success: false,
        message: "Doctor ID and Patient ID are required",
      };
    }

    const doctor = await UserModel.findById(doctorId);
    if (!doctor || doctor.role !== "doctor") {
      return { success: false, message: "Invalid doctor ID" };
    }

    const patient = await UserModel.findById(patientId);
    if (!patient || patient.role !== "patient") {
      return { success: false, message: "Invalid patient ID" };
    }

    // Validate X-ray image
    if (!xRayImage) {
      return { success: false, message: "X-ray image is required" };
    }

    // Build the full report object
    const report = new ReportModel({
      doctorId,
      patientId,
      xRayImage,
      keyFindings,
      heartSize,
      normalHeartSize,
      risk,
      aiConfidence,
      doctorNotes: doctorNotes || null,
      status: status || "completed",

      recommendedNextStep: {
        title,
        description,
      },
    });

    await report.save();

    return {
      success: true,
      data: report,
      message: "Report created successfully",
    };
  } catch (error: any) {
    return { success: false, message: error.message };
  }
};

// UPDATE REPORT (partial)
export const updateReport = async (
  reportId: string,
  updateData: Partial<any>,
) => {
  try {
    const report = await ReportModel.findByIdAndUpdate(
      reportId,
      { $set: updateData },
      { new: true, runValidators: true },
    );

    if (!report) {
      return { success: false, message: "Report not found" };
    }

    return {
      success: true,
      message: "Report updated successfully",
      data: report,
    };
  } catch (error: any) {
    return { success: false, message: error.message };
  }
};

// DELETE REPORT
export const deleteReport = async (reportId: string) => {
  try {
    const report = await ReportModel.findByIdAndDelete(reportId);

    if (!report) {
      return { success: false, message: "Report not found" };
    }

    return {
      success: true,
      message: "Report deleted successfully",
      data: report,
    };
  } catch (error: any) {
    return { success: false, message: error.message };
  }
};

// GET ALL REPORTS GENERATED BY A DOCTOR
export const getReportsGeneratedByDoctor = async (
  doctorId: string,
  filters: any,
) => {
  try {
    if (!doctorId) {
      return { success: false, message: "Doctor ID is required" };
    }

    const query: any = { doctorId };
    let sort: any = { createdAt: -1 };

    // TIME FILTER
    if (filters?.timeDate) {
      if (filters.timeDate === "thisWeek") {
        const oneWeekAgo = new Date();
        oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
        query.createdAt = { $gte: oneWeekAgo };
      } else if (filters.timeDate === "thisMonth") {
        const oneMonthAgo = new Date();
        oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
        query.createdAt = { $gte: oneMonthAgo };
      } else if (filters.timeDate === "today") {
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const tomorrow = new Date(today);
        tomorrow.setDate(tomorrow.getDate() + 1);
        query.createdAt = { $gte: today, $lt: tomorrow };
      }
    }

    // RISK FILTER
    if (filters?.riskLevel) {
      query.risk = filters.riskLevel;
    }

    // SORTING
    if (filters?.sortBy) {
      if (filters.sortBy === "timeDate") {
        sort = { createdAt: -1 };
      } else if (filters.sortBy === "name") {
        // sorting by populated field is allowed
        sort = { "patientId.name": 1 };
      }
    }

    // FINAL QUERY
    let reports = await ReportModel.find(query)
      .populate("patientId", "name email picture age gender")
      .sort(sort);

    // PATIENT NAME SEARCH
    if (filters?.search) {
      const regex = new RegExp(filters.search, "i");

      reports = reports.filter((report: any) =>
        regex.test(report?.patientId?.name),
      );
    }

    return {
      success: true,
      data: reports,
      message: "Reports retrieved successfully",
    };
  } catch (error: any) {
    return { success: false, message: error.message };
  }
};

// GET REPORTS FOR A PATIENT BY A DOCTOR
export const getPatientReportsGeneratedByDoctor = async (
  doctorId: string,
  patientId: string,
) => {
  try {
    const reports = await ReportModel.find({
      doctorId,
      patientId,
    })
      .populate("doctorId", "name email")
      .populate("patientId", "name email picture")
      .sort({ createdAt: -1 });

    return {
      success: true,
      data: reports,
      message: "Patient reports retrieved successfully",
    };
  } catch (error: any) {
    return { success: false, message: error.message };
  }
};

// REPORT COUNT PER DOCTOR
export const getPatientReportsGeneratedByDoctorCount = async (
  patientId: string,
) => {
  try {
    const result = await ReportModel.aggregate([
      {
        $match: {
          patientId: new mongoose.Types.ObjectId(patientId),
        },
      },
      {
        $sort: { createdAt: -1 },
      },
      {
        $group: {
          _id: "$doctorId",
          reportsCount: { $sum: 1 },
          latestReport: { $first: "$$ROOT" },
        },
      },
      {
        $lookup: {
          from: "users",
          localField: "_id",
          foreignField: "_id",
          as: "doctor",
        },
      },
      {
        $unwind: "$doctor",
      },
      {
        $project: {
          _id: 0,
          doctor: {
            _id: "$doctor._id",
            name: "$doctor.name",
            email: "$doctor.email",
            picture: "$doctor.picture",
          },
          reportsCount: 1,
          latestReport: 1,
        },
      },
    ]);

    return {
      success: true,
      message: "Report count retrieved successfully",
      data: result,
    };
  } catch (error: any) {
    return { success: false, message: error.message };
  }
};

// GET REPORTS FOR A PATIENT BY A DOCTOR
export const getPatientAllReports = async (patientId: string, filters?: any) => {
  try {

    const query: any = { patientId };

    if(filters?.riskLevel) {
      query.risk = filters.riskLevel;
    }
    

    let reports = await ReportModel.find(query)
      .populate("doctorId", "name email picture doctorInfo")
      .populate("patientId", "name email picture")
      .sort({ createdAt: -1 });


    if(filters?.search) {
      const regex = new RegExp(filters.search, "i");

      reports = reports.filter((report: any) =>
        regex.test(report?.doctorId?.name)
      );
    }


    return {
      success: true,
      data: reports,
      message: "Patient reports retrieved successfully",
    };
  } catch (error: any) {
    return { success: false, message: error.message };
  }
};
