import { Request, Response } from "express";
import {
  createReport,
  updateReport,
  deleteReport,
  getReportsGeneratedByDoctor,
  getPatientReportsGeneratedByDoctor,
  getPatientReportsGeneratedByDoctorCount,
  getPatientAllReports,
} from "../services/report.service";

// CREATE REPORT
export const createReportController = async (req: Request, res: Response) => {
  try {
    const { doctorId, patientId } = req.params;

    const files = req.files as
      | { [fieldname: string]: Express.Multer.File[] }
      | Express.Multer.File[];
    let pictureUrl: string | undefined;

    if (files) {
      if (Array.isArray(files)) {
        pictureUrl = files[0]?.path;
      } else {
        pictureUrl = files.xRayImage?.[0]?.path;
      }
    }

    const reportData = {
      ...req.body,
      doctorId,
      patientId,
      xRayImage: pictureUrl,
    };

    const result = await createReport(reportData);

    if (result.success) {
      res.status(201).json(result);
    } else {
      res.status(400).json(result);
    }
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Error creating report",
    });
  }
};

// UPATE REPORT
export const updateReportController = async (req: Request, res: Response) => {
  try {
    const { reportId } = req.params;

    const result = await updateReport(reportId, req.body);

    if (result.success) {
      res.status(200).json(result);
    } else {
      res.status(404).json(result);
    }
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Error updating report",
    });
  }
};

// DELETE REPORT
export const deleteReportController = async (req: Request, res: Response) => {
  try {
    const { reportId } = req.params;

    const result = await deleteReport(reportId);

    if (result.success) {
      res.status(200).json(result);
    } else {
      res.status(404).json(result);
    }
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Error deleting report",
    });
  }
};

// GET REPORTS GENERATED BY DOCTOR
export const getReportsGeneratedByDoctorController = async (
  req: Request,
  res: Response,
) => {
  try {
    const { doctorId } = req.params;
    const filters = req.query;
    const result = await getReportsGeneratedByDoctor(doctorId, filters);

    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Error fetching doctor reports",
    });
  }
};

// GET PATIENT REPORTS BY DOCTOR
export const getPatientReportsGeneratedByDoctorController = async (
  req: Request,
  res: Response,
) => {
  try {
    const { doctorId, patientId } = req.params;

    const result = await getPatientReportsGeneratedByDoctor(
      doctorId,
      patientId,
    );

    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Error fetching patient reports",
    });
  }
};

// GET PATIENT REPORTS BY DOCTOR
export const getPatientReportsGeneratedByDoctorCountController = async (
  req: Request,
  res: Response,
) => {
  try {
    const { patientId } = req.params;

    const result = await getPatientReportsGeneratedByDoctorCount(patientId);

    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Error fetching report counts",
    });
  }
};

// GET ALL REPORTS FOR A PATIENT
export const getPatientAllReportsController = async (
  req: Request,
  res: Response,
) => {
  try {
    const { patientId } = req.params;
    const filters = req.query;
    const result = await getPatientAllReports(patientId, filters);
    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Error fetching patient reports",
    });
  }
};
